// 首页
export const GOODSLIST_GET_SUCCESS = 'GOODSLIST_GET_SUCCESS'
export const GOODSLIST_NEXT = 'GOODSLIST_NEXT'
export const GOOD_GET_SUCCESS = 'GOOD_GET_SUCCESS'
export const GOODS_NEXT_BUTTON_CLOSE = 'GOODS_NEXT_BUTTON_CLOSE'

export const PHOTOSLIST_GET_SUCCESS = 'PHOTOSLIST_GET_SUCCESS'
export const PHOTOSLIST_NEXT = 'PHOTOSLIST_NEXT'
export const PHOTO_ADD_LIKE = 'PHOTO_ADD_LIKE'
export const PHOTOS_NEXT_BUTTON_CLOSE = 'PHOTOS_NEXT_BUTTON_CLOSE'
export const PHOTOSLIST_SEARCH = 'PHOTOSLIST_SEARCH'

export const BLOGSLIST_GET_SUCCESS = 'BLOGSLIST_GET_SUCCESS'
export const BLOGSLIST_NEXT = 'BLOGSLIST_NEXT'
export const BLOG_GET_SUCCESS = 'BLOG_GET_SUCCESS'
export const BLOGS_NEXT_BUTTON_CLOSE = 'BLOGS_NEXT_BUTTON_CLOSE'
export const BLOGSLIST_SEARCH = 'BLOGSLIST_SEARCH'

export const CHECK_SUCCESS = 'CHECK_SUCCESS'
export const CHECK_FAIL = 'CHECK_FAIL'
export const LOGIN = 'LOGIN_SUCCESS'
export const QUIT_SUCCESS = 'QUIT_SUCCESS'
